### ISSUE TITLE
How to use this in neovim?I can not find the rope and ropevim command in neovim.

### ISSUE THREAD

**Issue by meicale** [python-rope/ropevim#97]
I installed the plugin in neovim using packer and I also installed the rope, ropevim lib in conda virtual env using pip. I activate the conda env before I open neovim. But I cannot use the ropevim command, I can use the "help ropevim" and check the help manual, which means I have installed the plugin and I check the install location of my plugin to verify that.

**Comment by abdullatif-k** [comment]
I feel like this information should be a part of the documentation, but you actually need an additional configuration step. You need to enable [Neovim's python integration](https://neovim.io/doc/user/provider.html). The option to use a python provider is on by default, but you need to install the pynvim module.

`python3 -m pip install --user --upgrade pynvim`

Once you do that run `:Checkhealth` and make sure their is no issue with the python provider. You should see all the ropevim commands after. That's what was happening to me, Ropevim was failing silently because the python provider was not starting at all (because it can't find the pynvim module).

**Comment by lieryan** [comment]
Thanks for looking into this @abdullatif-k. I've added this to the documentation on #97.

@meicale if this does not resolve the issue you are having, please re-open a new issue.
